### ISSUE TITLE
Last rigth slash causes 404

### ISSUE THREAD

**Issue by joelsouza** [shockiii/kohana-multilang#2]
http://myhost/pt-br/

HTTP_Exception_404 [ 404 ]: Unable to find a route to match the URI: pt-br/

Route:

``` php
// Default
Route::set('default', '(<lang>(/<controller>(/<action>(/<id>))))', array('lang' => '(pt-br|en|es)'))
  ->defaults(array(
    'controller' => 'home',
    'action'     => 'index'
  ));
```

**Comment by shockiii** [comment]
Try `(<lang>/(<controller`, put the slash before the parenthesis.

**Comment by joelsouza** [comment]
Then the slash is required (wich is not an ideal comportament)

**Comment by shockiii** [comment]
Of course it is, you dont want 2 differents urls for the same page. You choose, it's either domain.tld/pt-br/ or domain.tld/pt-br.

But you do as you want, there is not limitation. I do this way cause this is an extension of the domain and it's like you're in a different directory.
domain.tld = domain.tld/pt-br/ = domain.tld/index.php = domain.tld/pt-br/index.php.
